# Generated by Django 5.2.7 on 2025-10-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('PROY', 'Proyector'), ('NOTE', 'Notebook'), ('IMPR', 'Impresora')], max_length=5)),
                ('estado', models.CharField(choices=[('OP', 'Operativo'), ('REP', 'En reparación'), ('BAJ', 'Dado de baja')], max_length=3)),
                ('fecha_ingreso', models.DateField()),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
    ]
